# -*- coding: utf-8 -*-
"""scaling_rag_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/soyfatointhewelt/06f989292e11c98edc3dfcaaf612adc5/scaling_rag_v1.ipynb

**Here, I havee all the data on a drive folder and will try to run a RAG to have some first answer approach of the data**
"""

# Reinstala LangChain, FAISS y dependencias
!pip install --upgrade pip
!pip install --upgrade langchain==1.1.2
!pip install --upgrade openai
!pip install --upgrade unstructured
!pip install --upgrade faiss-cpu
!pip install --upgrade tiktoken

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!pip install langchain-community

# Document loaders
# Para PDFs y Word
from langchain_community.document_loaders import UnstructuredPDFLoader, UnstructuredWordDocumentLoader

# Para archivos de texto, podemos hacer un loader simple
def TextLoader(path):
    with open(path, "r", encoding="utf-8") as f:
        return [{"page_content": f.read(), "metadata": {"source": path}}]

# Text splitting
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Vector store
from langchain_classic.vectorstores import FAISS
from langchain_classic.embeddings.openai import OpenAIEmbeddings

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os

# Carpeta donde están tus documentos
docs_path = "/content/drive/MyDrive/Scaling_Guidance_WWF"


# Listar archivos
all_files = []
for root, dirs, files in os.walk(docs_path):
    for file in files:
        if file.startswith("."):  # ignorar archivos ocultos como .DS_Store
            continue
        all_files.append(os.path.join(root, file))

print(f"Archivos encontrados: {all_files}")

!pip install pdfminer.six

!pip install pi_heif

!pip install unstructured-inference

# Instalar librerías necesarias
!apt-get install -y poppler-utils
!pip install pdf2image
!pip install unstructured-inference

# Instalar Tesseract OCR
!apt-get install -y tesseract-ocr
!pip install pytesseract unstructured-pytesseract

!pip install python-docx
!pip install pptx  # opcional si algún día quieres procesar .pptx

from tqdm.notebook import tqdm

all_documents = []

for f in tqdm(all_files):
    if f.lower().endswith(".pdf"):
        loader = UnstructuredPDFLoader(f)
        all_documents.extend(loader.load())
    elif f.lower().endswith((".doc", ".docx")):
        loader = UnstructuredWordDocumentLoader(f)
        all_documents.extend(loader.load())
    elif f.lower().endswith(".txt"):
        all_documents.extend(TextLoader(f))
    else:
        print(f"Ignorando archivo no soportado: {f}")

# Text splitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=150,
    separators=["\n\n", "\n", ".", "!", "?"]
)

all_texts = text_splitter.split_documents(all_documents)
print("Total chunks:", len(all_texts))

embeddings = OpenAIEmbeddings(api_key="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")
#this API sould be secret
vectorstore = FAISS.from_documents(
    documents=all_texts,
    embedding=embeddings
)

print("Vectorstore list size:", len(vectorstore.index.reconstruct_n(0, 1)))

client = OpenAI(api_key="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")

# 1. Create a text splitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=2000,      # safe for embedding models
    chunk_overlap=200
)

embedded_docs = []

# 2. Split and embed
for doc in all_documents:
    text = doc.page_content if hasattr(doc, "page_content") else doc.text
    chunks = text_splitter.split_text(text)

    for chunk in chunks:
        embedding = client.embeddings.create(
            model="text-embedding-3-large",
            input=chunk
        )
        embedded_docs.append({
            "text": chunk,
            "embedding": embedding.data[0].embedding
        })

"""✅ Next Steps (RAG Pipeline Finalization)"""

from langchain_classic.vectorstores import FAISS

# Create a dummy embedding class that returns precomputed vectors
class PrecomputedEmbeddings:
    def __init__(self, embeddings):
        self.embeddings = embeddings
        self.i = 0

    def embed_documents(self, texts):
        # Return embeddings in the same order they are requested
        res = self.embeddings[self.i:self.i+len(texts)]
        self.i += len(texts)
        return res

    def embed_query(self, text):
        # Not used here
        return None

embedding_function = PrecomputedEmbeddings(vectors)

index = FAISS.from_texts(
    texts=texts,
    embedding=embedding_function,
)

print("FAISS index created!")

import numpy as np

def retrieve(query, k=5):
    # 1. Embed the query
    query_embedding = client.embeddings.create(
        model="text-embedding-3-small",
        input=query
    ).data[0].embedding

    # 2. Convert to numpy
    query_vector = np.array(query_embedding).astype("float32")

    # 3. Search FAISS index
    scores, indices = index.index.search(np.array([query_vector]), k)

    # 4. Collect retrieved texts
    results = []
    for i in indices[0]:
        if i == -1:
            continue
        results.append(texts[i])

    return results

def retrieve(query, k=5):
    # 1. Embed the query with the SAME model used for documents
    query_embedding = client.embeddings.create(
        model="text-embedding-3-large",
        input=query
    ).data[0].embedding

    query_vector = np.array(query_embedding).astype("float32")

    # 2. Search in FAISS index
    scores, indices = index.index.search(np.array([query_vector]), k)

    # 3. Collect retrieved texts
    results = []
    for i in indices[0]:
        if i == -1:
            continue
        results.append(texts[i])

    return results

retrieve("What is the WWF scaling framework?")

def scaling_expert(query, k=5):
    # Step 1: retrieve relevant context
    context_chunks = retrieve(query, k)
    context = "\n\n".join(context_chunks)

    prompt = f"""
You are WWF's Scaling Expert GPT.

Use ONLY the context below to answer the question.
If information is missing, say: "This is not covered in the provided WWF documents."

Provide a structured, clean, well-formatted answer.

### CONTEXT
{context}

### QUESTION
{query}

### ANSWER
"""

    response = client.chat.completions.create(
        model="gpt-4.1",
        messages=[{"role": "user", "content": prompt}]
    )

    # FIXED LINE:
    return response.choices[0].message.content

scaling_expert("What is the WWF scaling framework?")

def scaling_expert(query, k=5):
    # Retrieve relevant context
    context_chunks = retrieve(query, k)
    context = "\n\n".join(context_chunks)

    prompt = f"""
You are **WWF's Scaling Expert GPT**, an AI trained on WWF scaling frameworks,
case studies, and tools. Your role is to provide *clear, strategic, professional-grade guidance*.

### OUTPUT REQUIREMENTS (Important)
Your response must follow these standards:

- **Professional WWF consulting tone:** clear, concise, strategic.
- **Executive Summary first** (3–5 bullet points).
- Use **headings + subheadings** to structure content logically.
- Use **markdown tables** when presenting options, pathways, agendas, or comparisons.
- Provide **actionable recommendations**, not generic statements.
- Only use information explicitly found in the provided context.
- If something is missing, state: *“This is not covered in the provided WWF documents.”*

---

### CONTEXT (from RAG)
{context}

### ❓ QUESTION
{query}

---

### YOUR PROFESSIONAL ANSWER
Provide:
1. **Executive Summary**
2. **Key Insights**
3. **Frameworks or Pathways involved**
4. **Actionable Recommendations**
5. **If relevant, examples from WWF scaling cases**

Use clean markdown formatting.
"""

    response = client.chat.completions.create(
        model="gpt-4.1",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content

scaling_expert("Explain the Core Challenges of this project of scaling")

